//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadgeInformation
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Status { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string CardCode { get; set; }
        public string HotStamp { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public int EmployeeNumber { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
