//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.LocationCategories = new HashSet<LocationCategory>();
            this.Programs = new HashSet<Program>();
            this.Programs1 = new HashSet<Program>();
        }
    
        public long locationID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string hours { get; set; }
        public string phones { get; set; }
        public string url { get; set; }
        public string image_url { get; set; }
        public string email { get; set; }
        public string organization { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography point { get; set; }
        public bool isCounty { get; set; }
        public Nullable<decimal> lms_post_id { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
        public string operatedByLabel { get; set; }
        public string source { get; set; }
        public Nullable<int> sourceID { get; set; }
        public string nameUrlFriendly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationCategory> LocationCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs1 { get; set; }
    }
}
