//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationCategory
    {
        public int locationCategoryID { get; set; }
        public long locationID { get; set; }
        public long categoryID { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
