//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int programID { get; set; }
        public long locationID { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public string minAge { get; set; }
        public string maxAge { get; set; }
        public string displayAge { get; set; }
        public string feeStructure { get; set; }
        public bool registrationRequired { get; set; }
        public string registrationFee { get; set; }
        public string frequencyType { get; set; }
        public string frequency { get; set; }
        public string specialCriteria { get; set; }
        public Nullable<int> programCategoryID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual ProgramCategory ProgramCategory { get; set; }
        public virtual ProgramCategory ProgramCategory1 { get; set; }
    }
}
