//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripId { get; set; }
        public int EmployeeId { get; set; }
        public double FinalOdometer { get; set; }
        public System.DateTime FinishTime { get; set; }
        public double InitialOdometer { get; set; }
        public string ProjectFunction { get; set; }
        public string ProjectTitle { get; set; }
        public string Purpose { get; set; }
        public System.DateTime StartTime { get; set; }
        public string TaskOrder { get; set; }
        public string TripPath { get; set; }
        public int VehicleId { get; set; }
        public Nullable<bool> Approval { get; set; }
        public Nullable<bool> Legal { get; set; }
        public Nullable<bool> Reviewed { get; set; }
        public Nullable<bool> AuthorizedDriver { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
