//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public int VehicleId { get; set; }
        public string Color { get; set; }
        public System.DateTime LastService { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string ModelTrim { get; set; }
        public Nullable<System.DateTime> ModelYear { get; set; }
        public System.DateTime NextService { get; set; }
        public double Odometer { get; set; }
        public string PlateNumber { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
